# cargo-about configuration
# https://embarkstudios.github.io/cargo-about/

accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
    "BSL-1.0",
    "CC0-1.0",
    "OpenSSL",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
targets = ["wasm32-unknown-unknown"]
