[book]
authors = ["dalance"]
language = "en"
src = "src"
title = "The Veryl Hardware Description Language"
description = "Veryl is a modern hardware description language designed as a SystemVerilog alternative. This is the official reference book covering language features, code examples, and the development environment."

[build]
extra-watch-dirs = ["po"]

[preprocessor.curl]
command = "./fetch-grammar.sh"

[preprocessor.veryl]

[preprocessor.gettext]
after = ["links"]

[output.html]
additional-css = [
  "theme/css/language-picker.css",
  "theme/css/veryl.css",
]
additional-js = [
  "mode-veryl.js",
  "veryl-init.js",
  "theme/language-picker.js",
]

[output.html.fold]
enable = true
level  = 1

[output.html.playground]
editable = true
line-numbers = false
